### ISSUE TITLE
ERROR! 'include_vars' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by matjam** [cmacrae/ansible-sensu#149]
this can't be right .. but this is what I get.

```
chrome@ORAC:/mnt/c/Users/chrome/Development/sensu-ansible$ ansible --version
ansible 2.4.3.0
  config file = None
  configured module search path = ['/home/chrome/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Aug 18 2017, 17:48:00) [GCC 5.4.0 20160609]
chrome@ORAC:/mnt/c/Users/chrome/Development/sensu-ansible$ ansible-playbook -i inventory -b -K tasks/main.yml
SUDO password:
ERROR! 'include_vars' is not a valid attribute for a Play

The error appears to have been in '/mnt/c/Users/chrome/Development/sensu-ansible/tasks/main.yml': line 4, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - include_vars: "{{ ansible_distribution }}.yml"
    ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```

I'm using ansible on the linux subsystem for windows ubuntu distribution, which is why there's the weird paths.

Any ideas? I'm pretty new to ansible.

**Comment by matjam** [comment]
get the same thing when running it on the server I'm trying to deploy to.

**Comment by matjam** [comment]
oh, i'm an idiot,

**Comment by matjam** [comment]
I wish I knew how to use this. I created a playbook but then it complains about lack of roles?

**Comment by matjam** [comment]
Is there step by step instructions somewhere on how to execute this playbook? I don't see how its done, and ansible docs don't help.

**Comment by jaredledvina** [comment]
Hey @matjam,

I see this issue is closed but, wanted to follow up to ensure you got everything sorted out. 
The purpose of this repo is to store the Sensu Ansible role. Role's are a concept inside Ansible that's verify similar to modules in the Puppet work, and cookbooks in the Chef world. A role, is just a defined collection of Ansible playbooks, variables, and settings, that can be executed as a whole and applied to your target hosts. Checkout the official Ansible docs for more specifics on Ansible Roles: http://docs.ansible.com/ansible/latest/playbooks_reuse_roles.html

This role, should be pretty simple to deploy for a single host (assume that's your target currently), currently https://ansible-sensu.readthedocs.io/en/latest/single_master/ is the best documentation for how to do that. 

If you've never used Ansible before, I would strongly recommend working through all of the Introduction docs here: http://docs.ansible.com/ansible/latest/intro.html

Finally https://www.ansible.com/resources/get-started also links to a lot of good resources. 

Happy to help further, let me know if the above is useful!

**Comment by matjam** [comment]
sorry, I figured it out eventually. I was trying to use it like a playbook, like you said, but it's a role.

Thanks for taking the time to respond anyway :-)
