### ISSUE TITLE
How about HA deployments?

### ISSUE THREAD

**Issue by ppetit** [cmacrae/ansible-sensu#186]
Hi there!
I am somewhat confused by this role w.r.t to implementing distributed deployments. In practice sensu-server and sensu-api can be replicated for scale and HA since, to the best of my knowledge, they are stateless (putting RabbitMQ and Redis aside). So what's the idea behind that sentence in the documentation? I quote: "**_Since we only want one Sensu master, the default to act as a master in this role is set to false - defined by sensu_master_**".  There is no such thing as a sensu master right?  What do you mean by that? And so the question. How are supposed to use that role if one wanted to replicate sensu-server and sensu-api and uchiwa on multiple nodes? Should I define those nodes as sensu master (whereby _**sensu_master: false**_ simply means sensu client) or is there something else that I missed? Thanks in advance for the clarification.
-P

**Comment by jaredledvina** [comment]
Hey @ppetit ,

Sorry about the lag on replying to your issue! As is written up in https://github.com/sensu/sensu-ansible/issues/72, currently, this role doesn't support splitting out the Sensu API and server components but, if you are interested, I'm happy to review a PR adding that support. I understand the term 'master' is confusing, I guess, it's to imply the server running the sensu "backend" components (so server, api, and then if you want RabbitMQ, Redis, and Uchiwa). 

For multiple masters, I think you'll want to ensure they have `sensu_master` set to true for those servers, and then include them in the `sensu_masters` host group. It's been a while since I've used this role personally to deploy sensu to multiple masters, but I think that'll do the trick. 

Let me know if you run into any other issues, happy to help! We're also on the Sensu Community Slack in `#ansible`: https://sensu.io/community

**Comment by ppetit** [comment]
Hi Jared,
Thanks for the clarification. I am in middle to trying deploying multiple "masters" and let you guys know of issues if any..

**Comment by jaredledvina** [comment]
Going to close this issue out, feel free to re-open if there's any remaining questions though!
