### ISSUE TITLE
become_user is not a legal parameter in an Ansible task or handler

### ISSUE THREAD

**Issue by RiRa12621** [cmacrae/ansible-sensu#37]
so i wonder how this can ever have worked at all 

`become_user is not a legal parameter in an Ansible task or handler`

because this is in multiple places 

`rrackow$ git grep become_user
handlers/main.yml:    become_user: "{{ sensu_user_name }}”
tasks/FreeBSD/dashboard.yml:    become_user: "{{ sensu_user_name }}”
tasks/SmartOS/dashboard.yml:    become_user: "{{ sensu_user_name }}”
tasks/rabbit.yml:    become_user: rabbitmq
tasks/ssl_generate.yml:    become_user: "{{ sensu_user_name }}”`

**Comment by cmacrae** [comment]
Well, in all my time writing Ansible code, since 'become' was made available: it most certainly is a valid parameter in tasks, and therefore; handlers.

Granted, I haven't written Ansible code in quite some time, and they have been busy with releases.

Could you please expand on exactly how you encounter this issue?

**Comment by RiRa12621** [comment]
i am using packer with local Ansible 2.1.1 on Mac OS when getting this error
tbh I am not really an Ansible expert because we just recently moved to it so if you need any more details it would be nice to be as precise as possible 
update: i just downgraded to 2.0.2 and the same error message comes up

**Comment by smuth4** [comment]
The version available in MacOS's homebrew repo is 1.9.2, which wouldn't have the become_user option. Are you sure that's not the version being used accidentally?

**Comment by RiRa12621** [comment]
not sure how you come to that 
`rrackow$ ansible --version
ansible 2.1.1.0`

and that is installed via homebrew

**Comment by smuth4** [comment]
Brew would've installed 1.9.2 on my Mac, that's why I asked:

```
$ brew info ansible
ansible: stable 1.9.2 (bottled), HEAD
Automate deployment, configuration, and upgrading
http://www.ansible.com/home
/usr/local/Cellar/ansible/1.9.2 (3594 files, 42M) *
```

But even that wouldn't make sense either, since all `become_user`s in the code are preceded by a `become` which should be the thing that causes it to choke. Can you post the full error message? In particular, there should be a line that starts with `The error appears to have been in` that will mention what file the error occurred in.

**Comment by jaredledvina** [comment]
Hey @RiRa12621, 

I'm going to close this out due to inactivity but, if you're still hitting this issue let me know and I'll work with you to troubleshoot!
