### ISSUE TITLE
Support for multi-server installation

### ISSUE THREAD

**Issue by jaykumar-jnpr** [cmacrae/ansible-sensu#39]
It would be nice if this role could do a multi-server installation with 
1. Clustered RabbitMQ
2. Clustered Redis (Sentinel)
3. Multiple servers running sensu-server & sensu-api
4. Multiple servers running uchiwa
5. Throw in HAproxy and Keepalived to remove any single point of failure.

**Comment by smuth4** [comment]
1, 2 and 5 are probably out of scope for this project. 3 is handled automagically by sensu, just have multiple nodes running this role with `sensu_master = true`, and if they're using the same transport/persistence endpoints then they'll do clustering on their own. I'm not sure I see the point of 4, but again, you can just point the configs at the same endpoints.

**Comment by danielkza** [comment]
@smuth4 Currently this isn't the case, as some actions attempt to delegate directly to `sensu_api_host`, which doesn't make sense in an HA environment.

**Comment by smuth4** [comment]
Hm, that's a fair point, I'll spin up a second "master" and see if I can come up with something that makes sense while keeping the scope of this role sensible.

**Comment by danielkza** [comment]
@smuth4 What I've done for now is to remove delegation completely. I believe it is fine, as any changes that require services from the master to restart will actually _happen on that same master_ eventually. At that time, the handlers should be triggered and do their job.

I also found a couple more changes necessary for my use case. I want to have a multi-master setup that can self-bootstrap on AWS (without requiring an external Ansible machine driving the play). I'm not sure which ones are appropriate to upstream, so tell me what you think:
- Decouple the API port served by Sensu and used by Uchiwa, so that I can set up nginx or an Amazon ELB in front of the API instances
- Fix the SSL configuration to not assume the names of the source files and always for the destinations to be named correctly.
- Make it possible to copy the SSL certificates with `remote_src: yes`, as I am pulling them from Amazon S3 to each machine before including the role.

**Comment by smuth4** [comment]
> @smuth4 What I've done for now is to remove delegation completely. I believe it is fine, as any changes that require services from the master to restart will actually happen on that same master eventually. At that time, the handlers should be triggered and do their job.

Did a quick review and I agree, though I'll want to do some quick testing on my own before actually removing them.

> Decouple the API port served by Sensu and used by Uchiwa, so that I can set up nginx or an Amazon ELB in front of the API instances
> 
> Make it possible to copy the SSL certificates with remote_src: yes, as I am pulling them from Amazon S3 to each machine before including the role.

👍 

> Fix the SSL configuration to not assume the names of the source files and always for the destinations to be named correctly.

I'm not sure I fully understand what this means, but I'd definitely be up for a PR as long as it doesn't affect the defaults.

**Comment by danielkza** [comment]
@smuth4

> Did a quick review and I agree, though I'll want to do some quick testing on my own before actually removing them.

I pushed it in #55, if you want to test it out. The changes are really simple though.

> 👍

See #52 #54.

> I'm not sure I fully understand what this means, but I'd definitely be up for a PR as long as it doesn't affect the defaults.

See #53.

**Comment by jaredledvina** [comment]
Hey @danielkza, 

I'm trying to burn down the backlog of issues here, reading through this, it appears that a few PR's have already been merged to address this issue. 

Anything remaining to address here?

**Comment by danielkza** [comment]
Hi @jaredledvina! I'm no longer using Sensu (and consequently sensu-ansible), but at the time the changes I needed were merged. So feel free to close this if you prefer, but I can't tell if all the other requests on the original post were fulfilled.

**Comment by jaredledvina** [comment]
Sweet, for the time being, I'll close this out. Let me know if anyone wants to revisit anything and I can reopen the issue.
